# Set to true to add assignees to pull requests
addAssignees: true

assignees:
  - ryamaguchi0220
  
numberOfAssignees: 1

# A list of keywords to be skipped the process that add reviewers if pull requests include it 
skipKeywords:
  - wip
